{
    "title": "6-Max RFI Ranges",
    "utg": {
        "1.0": "AQo+, A5s, A9s+, KTs+, QTs+, JTs+, 77+",
        "0.5": "ATo-AJo, KJo-KQo, A2s-A4s, A6s-A8s, K8s-K9s, Q9s, J9s, T8s, 97s-98s, 87s, 76s, 65s, 44-55"
    },
    "hj": {
        "1.0": "AJo+, KQo, A2s+, K9s+, Q9s+, J9s+, T8s+, 97s+, 87s, 76s, 55+",
        "0.5": "A9o-ATo, KTo-KJo, QTo-QJo, K6s-K8s, Q8s, J8s, 86s, 75s, 65s, 54s, 22-44"
    },
    "co": {
        "1.0": "A9o+, KTo+, QJo, A2s+, K8s+, Q9s+, J9s+, T8s+, 97s+, 86s+, 75s+, 65s+, 54s, 44+",
        "0.5": "A8o, K9o, QTo, JTo, T9o, K2s-K7s, Q5s-Q8s, J6s-J8s, T6s-T7s, 96s, 85s, 64s, 53s, 43s"
    },
    "btn": {
        "1.0": "A6o+, K8o+, Q9o+, J9o+, T9o+, 98o, A2s+, K2s+, Q5s+, J6s+, T6s+, 96s+, 85s+, 75s+, 64s+, 54s, 43s, 22+",
        "0.5": "A2o-A5o, K7o, Q8o, J8o, T8o, 97o, 87o, 76o, Q2s-Q4s, J2s-J5s, T2s-T5s, 92s-95s, 82s-84s, 72s-74s, 62s-63s, 52s-53s, 42s, 32s"
    },
    "sb": {
        "1.0": "A4o+, K8o+, Q8o+, J9o+, T9o+, 98o, A2s+, K2s+, Q4s+, J5s+, T6s+, 96s+, 85s+, 75s+, 65s+, 54s, 22+",
        "0.5": "A2o-A3o, K6o-K7o, Q2s-Q3s, J2s-J4s, T2s-T5s, 92s-95s, 82s-84s, 72s-74s, 6s-64s, 52s-53s, 42s, 32s"
    }
}
